### PR TITLE
Added comments in Warnings and Earthquakes

### PR DESCRIPTION
**Pull request by miguelcarreiro**

### CODE REVIEW

**Comment by JorgeMiguelGomes** [comment]
Looks **very** good to me. Waiting on @tiagojpdias to give ok **to merge**

**Comment by tiagojpdias** [comment]
@miguelcarreiro was expecting something more like this:

```js

/**
 * Get earthquake events
 *
 * @param {Client} client 
 */
const getEarthquakes = async (client) => {
  const yesterday = moment().subtract(1, 'days');
  ...
```

Commenting functions using this approach (which all IDEs have the ability to generate) enhances type hinting.

I'll accept the PR for now but wanted to leave this remark for the future.

Cheers,

**Review by tiagojpdias — APPROVED** [review]

**Comment by miguelcarreiro** [comment]
> @miguelcarreiro was expecting something more like this:
> 
> ```js
> /**
>  * Get earthquake events
>  *
>  * @param {Client} client 
>  */
> const getEarthquakes = async (client) => {
>   const yesterday = moment().subtract(1, 'days');
>   ...
> ```
> 
> Commenting functions using this approach (which all IDEs have the ability to generate) enhances type hinting.
> 
> I'll accept the PR for now but wanted to leave this remark for the future.
> 
> Cheers,

Thanks for the feedback!

I'll fix the comments using your approach and create another PR using 'comments' branch.

**Comment by miguelcarreiro** [comment]
Created a new pull request (https://github.com/vostpt/bot/pull/41), because I had to create a new branch with a new name, in order to adapt to the new branching strategy.

**Pull request merged**
