### PR TITLE
[BOT-161] Add md5sum to DGS reports

### PR DESCRIPTION
**Pull request by joaoleveiga**
## Description
This pull request addresses issue [BOT-161](https://github.com/vostpt/bot/issues/161).

## Task items:
- [x] Fixed issue BOT-161;
- [x] Added md5sum to reports based on their content;
- [x] Added migration to create new `md5sum` field;
~Added migration to fill in this field if the database has previous reports;~
- [x] Updated the documentation on how to run migrations;
- [x] Ran `eslint --fix ./src`

### CODE REVIEW

**Comment by joaoleveiga** [comment]
A few notes:
* If you prefer, the algorithm can be changed to sha256 instead of md5.
* I still didn't do the migration script to update the checksums of reports alread present in the database. I'll try to figure that out tomorrow.

**Comment by miguelcarreiro** [comment]
> A few notes:
> 
> * If you prefer, the algorithm can be changed to sha256 instead of md5.
I don't have any preference in the algorithm, so, if you decided to use md5, I think there's no need to change algorithm to sha256.

> * I still didn't do the migration script to update the checksums of reports alread present in the database. I'll try to figure that out tomorrow.
Ok, no problem! I'll wait for the script to merge PR into `master`.

**Comment by joaoleveiga** [comment]
@miguelcarreiro Whenever you can, can you please take a look at the migration file? I think I have probably tried 5 different approaches already and I still can't seem to understand how can I update the rows.

What's happening is that when I run the migration, it correctly fetches all the reports, and their md5sum, and tries to update. **However**, when committing the transaction (I think), only the last md5sum is used for _all the rows_ :sob:

**Comment by joaoleveiga** [comment]
Updating the PR, as per our discussion on Discord about dropping the migration bit that updates the data.

**Review by miguelcarreiro — APPROVED** [review]

**Pull request merged**
